"""Turning a question plus a schema into SQL, and repairing it when it fails.

THE REPAIR PROMPT IS THE MOST IMPORTANT THING IN THIS FILE.
When SQL fails, SQLite says exactly why: `no such column: revenue`. That is a
precise, free correction signal generated by the only authority that matters --
far better than a second model grading the first. The repair prompt shows the
model its own query and that message and asks for a fix.
"""

from __future__ import annotations

import re

import httpx

from .config import (GENERATION_TIMEOUT_S, GENERATOR, GROQ_API_KEY,
                     GROQ_MODEL, OLLAMA_URL, OLLAMA_MODEL,
                     GENERATION_TIMEOUT_S as _T)

SYSTEM = """You translate questions into SQLite SQL.

Rules:
- Use ONLY the tables and columns shown. Do not invent names.
- Return a single SELECT statement. No INSERT, UPDATE, DELETE, DROP or PRAGMA.
- No explanation, no markdown fences. SQL only.
- Prefer explicit JOINs using the foreign keys listed.
- When the question implies a ranking or a "top N", use ORDER BY with LIMIT."""

REPAIR = """The SQL you wrote failed. Fix it.

Change as little as possible: the error names one problem, so correct that
rather than rewriting the query. Return SQL only."""


def build_prompt(question: str, schema_docs: list[str]) -> str:
    schema = "\n\n".join(schema_docs)
    return f"{schema}\n\nQuestion: {question}\nSQL:"


def build_repair_prompt(question: str, schema_docs: list[str],
                        bad_sql: str, error: str) -> str:
    return (f"{build_prompt(question, schema_docs)}\n\n"
            f"You wrote:\n{bad_sql}\n\n"
            f"The database said:\n{error}\n\nCorrected SQL:")


def clean(raw: str) -> str:
    """Models wrap SQL in fences and prefixes no matter how firmly you ask them
    not to. Strip rather than reject -- a formatting habit is not a wrong answer."""
    s = raw.strip()
    s = re.sub(r"^```(?:sql)?\s*|\s*```$", "", s, flags=re.S).strip()
    s = re.sub(r"^(SQL|Query|Answer)\s*:\s*", "", s, flags=re.I).strip()
    return s.rstrip(";").strip()


class MockGenerator:
    """Writes a trivially valid query against the first table it is shown.

    Not a stub -- it is the FLOOR. It proves the pipeline runs end to end with
    no API key (which is what the tests use), and it gives you the score of
    "valid SQL that ignores the question". If your real model is not far above
    this, something is wrong that an accuracy number alone would not reveal.
    """

    name = "mock"

    def generate(self, question: str, schema_docs: list[str]) -> str:
        for doc in schema_docs:
            m = re.search(r"^Table:\s*(\S+)", doc, re.M)
            if m:
                return f'SELECT * FROM "{m.group(1)}" LIMIT 5'
        return "SELECT 1"

    def repair(self, question, schema_docs, bad_sql, error) -> str:
        return self.generate(question, schema_docs)


class GroqGenerator:
    name = "groq"

    def __init__(self):
        self._client = httpx.Client(timeout=GENERATION_TIMEOUT_S)

    def _call(self, system: str, user: str) -> str:
        # Groq's free tier rate-limits per minute. A single 429 mid-benchmark
        # would otherwise kill the whole run over one transient limit, so
        # retry with backoff before giving up -- this is about pacing, not
        # a broken key or a bad request, so it's handled separately from the
        # SQL repair loop (§graph.py), which is for invalid queries, not
        # rate limits.
        import time

        last_exc: Exception | None = None
        for attempt in range(5):
            r = self._client.post(
                "https://api.groq.com/openai/v1/chat/completions",
                headers={"Authorization": f"Bearer {GROQ_API_KEY}"},
                json={
                    "model": GROQ_MODEL,
                    "messages": [{"role": "system", "content": system},
                                 {"role": "user", "content": user}],
                    # 0.0 because a benchmark that returns different numbers on
                    # re-run measures nothing.
                    "temperature": 0.0,
                    "max_tokens": 500,
                },
            )
            if r.status_code != 429:
                r.raise_for_status()
                return clean(r.json()["choices"][0]["message"]["content"])
            # Respect Retry-After if Groq sends one, else exponential backoff.
            wait = float(r.headers.get("retry-after", 2 ** attempt))
            print(f"  429 rate limited, waiting {wait:.0f}s "
                  f"(attempt {attempt + 1}/5) ...")
            time.sleep(wait)
            last_exc = httpx.HTTPStatusError(
                "rate limited", request=r.request, response=r)
        raise last_exc

    def generate(self, question: str, schema_docs: list[str]) -> str:
        return self._call(SYSTEM, build_prompt(question, schema_docs))

    def repair(self, question, schema_docs, bad_sql, error) -> str:
        return self._call(
            SYSTEM + "\n\n" + REPAIR,
            build_repair_prompt(question, schema_docs, bad_sql, error))


class OllamaGenerator:
    """Same contract as GroqGenerator, pointed at a local Ollama server instead
    of a hosted API. Ollama exposes an OpenAI-compatible endpoint, so the call
    shape is identical -- no auth header, and no rate-limit retry loop, since
    there's no per-minute quota against your own machine. What you trade for
    "free and offline" is model size: a 7-14B local model is not the 70B model
    Groq serves for free, and text-to-SQL accuracy tracks model size closely,
    so expect a real gap against the same benchmark, not just a slower call.
    """

    name = "ollama"

    def __init__(self):
        self._client = httpx.Client(timeout=GENERATION_TIMEOUT_S)

    def _call(self, system: str, user: str) -> str:
        r = self._client.post(
            f"{OLLAMA_URL}/v1/chat/completions",
            json={
                "model": OLLAMA_MODEL,
                "messages": [{"role": "system", "content": system},
                             {"role": "user", "content": user}],
                # Same reasoning as GroqGenerator: 0.0 so a re-run of the
                # benchmark measures the same thing twice, not noise.
                "temperature": 0.0,
                "max_tokens": 500,
            },
        )
        r.raise_for_status()
        return clean(r.json()["choices"][0]["message"]["content"])

    def generate(self, question: str, schema_docs: list[str]) -> str:
        return self._call(SYSTEM, build_prompt(question, schema_docs))

    def repair(self, question, schema_docs, bad_sql, error) -> str:
        return self._call(
            SYSTEM + "\n\n" + REPAIR,
            build_repair_prompt(question, schema_docs, bad_sql, error))


def get_generator():
    if GENERATOR == "groq":
        return GroqGenerator()
    if GENERATOR == "ollama":
        return OllamaGenerator()
    return MockGenerator()
